### PR TITLE
Project structure initialization

### PR DESCRIPTION
**Pull request by wfdewith**
This pull request contains the initial structure of the project.
- Resource files for string localization
- View, ViewModel and Model folders for code organization (ViewModel and Model are not visible at the moment because they are empty. They are defined in the csproj file though.)
- An entry point that starts the program and shows the MainWindow
- A basic MainWindow
- AssemblyInfo.cs for release information
- StyleCop settings

### CODE REVIEW

**Comment by borisroman** [comment]
LGTM 👍

**Comment by AdriaanDeVos** [comment]
Shouldn't there be a README in the root?

**Comment by wfdewith** [comment]
I'm working on that and I will make a new PR for that

**Comment by AdriaanDeVos** [comment]
Ok, it works perfect!

**Comment by cbabrunal** [comment]
Working on my desktop np.

**Comment by keohnoel** [comment]
Works here too

**Pull request merged**
