### PR TITLE
Add basic connect window and a map view placeholder

### PR DESCRIPTION
**Pull request by wfdewith**
I'm sorry about the size of this commit, but that's because I had to rewrite everything a couple of times.

### CODE REVIEW

**Comment by cbabrunal** [comment]
k got it working. hard to reinstall .Net 4.6.1

**Comment by AdriaanDeVos** [comment]
Stylecop passed perfect but I do get a warning during the build phase. Is it needed/possible to resolve this?
"The event 'RelayCommand.CanExecuteChanged' is never used"

Nonetheless, the screen looks slick!

**Comment by wfdewith** [comment]
I don't know why that happens, but CanExecuteChanged needs to be implemented because of the interface, and yet Visual Studio warns about it.

I could probably disable this specific warning, but I'm not sure if that's the way to go.

**Comment by cbabrunal** [comment]
Works here!!!

**Comment by AdriaanDeVos** [comment]
Ok, :+1:

**Pull request merged**
