### PR TITLE
Add map rendering

### PR DESCRIPTION
**Pull request by wfdewith**

### CODE REVIEW

**Comment by keohnoel** [comment]
LGTM

**Comment by wfdewith** [comment]
@cbabrunal, why'd you add your commit to this branch?

**Comment by cbabrunal** [comment]
We will fix this later today. I made mistake actually

**Comment by keohnoel** [comment]
Thnx for catching the faulty commit. And LGTM

**Comment by cbabrunal** [comment]
LGTM

**Comment by wfdewith** [comment]
Merged in 3157705207281690ed3f81c6a999bddd4c06bd73 and ac72e88feeb3c9830022c42414093510c9de4790

**Pull request closed without merging**
