### PR TITLE
Prototypes

### PR DESCRIPTION
**Pull request by AdriaanDeVos**
Add the remaining prototypes that exist in the Unity world to the HiVRClient.

Only the character.model is missing but that one will be dynamic.

### CODE REVIEW

**Comment by wfdewith** [comment]
It looks good, but next time I'd update the csproj file per commit. I know you committed after you wrote them all, but next time I'd just commit after completing one class, or maybe even squash it all in one commit.

**Comment by wfdewith** [comment]
Oh, and the same for tests

**Comment by AdriaanDeVos** [comment]
Sourcetree didn't show the changes after I already commited 4 new files...
Good point. I'll look at it the next time.

**Comment by wfdewith** [comment]
It's not really a big problem, but it's nicer when commits are atomic

**Comment by cbabrunal** [comment]
LGTM

**Pull request merged**
